import os

base_dir = r"C:\Users\nelso\OneDrive\Desktop\autonomous-dev-factory-v3"

files = {
    "requirements.txt": """pyyaml
google-genai
""",
    "README.md": """# Autonomous Dev Factory v3 (AI Generation Engine) 🚀

This is the next-generation autonomous DevOps factory. Instead of copying static boilerplates, it uses the **Gemini AI API** to dynamically generate actual FastAPI endpoints, React components, Database schemas, and tests based on your `spec.yaml` file.

## Setup
1. `pip install -r requirements.txt`
2. Set your Gemini API key:
   - PowerShell: `$env:GEMINI_API_KEY="your-api-key"`
   - Bash: `export GEMINI_API_KEY="your-api-key"`
3. Run the factory:
   `python devfactory.py --spec specs/example.yaml`
""",
    "specs/example.yaml": """project:
  name: dynamic-ai-saas
  type: fastapi-react
  visibility: public

  stack:
    backend: fastapi
    db: postgres
    frontend: react

  features:
    - User authentication with JWT
    - Role Based Access Control (RBAC)
    - Product management CRUD

  github:
    auto_create: false
    auto_push: false
    auto_release: false
    auto_pin: false
""",
    "cli/__init__.py": "",
    "cli/parser.py": """import yaml

def load_spec(path: str):
    with open(path, "r") as f:
        return yaml.safe_load(f)
""",
    "cli/generator.py": """import os
from engines.ai_engine import generate_code_with_ai

def generate_project(spec):
    name = spec["project"]["name"]
    base = f"outputs/generated_repos/{name}"
    
    os.makedirs(base, exist_ok=True)
    os.makedirs(f"{base}/backend", exist_ok=True)
    os.makedirs(f"{base}/frontend", exist_ok=True)

    print(f"🧠 Generating project {name} with AI Engine...")
    
    # Generate Backend (FastAPI)
    print("-> Generating FastAPI Backend...")
    features = ", ".join(spec["project"]["features"])
    backend_code = generate_code_with_ai(f"Write a full FastAPI main.py file with the following features: {features}. Only return the python code.")
    
    # Strip markdown block if present
    if backend_code.startswith("```python"):
        backend_code = backend_code.split("```python")[1].split("```")[0].strip()
        
    with open(f"{base}/backend/main.py", "w", encoding="utf-8") as f:
        f.write(backend_code)

    # Generate Frontend (React)
    print("-> Generating React Frontend...")
    frontend_code = generate_code_with_ai(f"Write a React App.jsx component dashboard that supports these features: {features}. Only return the JSX code.")
    
    if frontend_code.startswith("```jsx"):
        frontend_code = frontend_code.split("```jsx")[1].split("```")[0].strip()
    elif frontend_code.startswith("```javascript"):
        frontend_code = frontend_code.split("```javascript")[1].split("```")[0].strip()
        
    with open(f"{base}/frontend/App.jsx", "w", encoding="utf-8") as f:
        f.write(frontend_code)

    # README
    with open(f"{base}/README.md", "w") as f:
        f.write(f"# {name}\\n\\nAuto-generated by DevFactory v3 (AI Engine)\\n\\nFeatures:\\n")
        for feature in spec["project"]["features"]:
            f.write(f"- {feature}\\n")

    print(f"✅ Generated AI-powered repository at {base}")
    return base
""",
    "engines/__init__.py": "",
    "engines/ai_engine.py": """import os
import sys

try:
    from google import genai
except ImportError:
    print("ERROR: Please install google-genai using 'pip install google-genai'")
    sys.exit(1)

def generate_code_with_ai(prompt: str) -> str:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("WARNING: GEMINI_API_KEY environment variable not set. Falling back to dummy generation.")
        return "# Dummy generated code\\n# Please set GEMINI_API_KEY to use real AI generation\\n\\nprint('Set API key to generate real code')"
    
    try:
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=f"You are an expert software engineer. {prompt}"
        )
        return response.text
    except Exception as e:
        print(f"AI Generation Error: {e}")
        return f"# Error during generation: {e}"
""",
    "github/__init__.py": "",
    "github/git_manager.py": """import subprocess

def init_git(path):
    print("-> Initializing Git...")
    subprocess.run(["git", "init"], cwd=path, stdout=subprocess.DEVNULL)
    subprocess.run(["git", "add", "."], cwd=path, stdout=subprocess.DEVNULL)
    subprocess.run(["git", "commit", "-m", "Auto-generated by DevFactory v3 AI"], cwd=path, stdout=subprocess.DEVNULL)
    subprocess.run(["git", "branch", "-M", "main"], cwd=path, stdout=subprocess.DEVNULL)
""",
    "devfactory.py": """import argparse
import sys
from cli.parser import load_spec
from cli.generator import generate_project
from github.git_manager import init_git

def main():
    parser = argparse.ArgumentParser(description="Autonomous DevFactory v3 (AI Engine)")
    parser.add_argument("--spec", required=True, help="Path to the spec YAML file")
    args = parser.parse_args()

    try:
        spec = load_spec(args.spec)
        project_path = generate_project(spec)
        init_git(project_path)
        print("\\n🚀 Dev Factory v3 AI generation completed successfully!")
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
"""
}

for file_path, content in files.items():
    full_path = os.path.join(base_dir, file_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(content)

print(f"Autonomous Dev Factory v3 has been scaffolded at: {base_dir}")
